CREATE TYPE "public"."participant_role" AS ENUM('host', 'guest');--> statement-breakpoint
CREATE TYPE "public"."room_status" AS ENUM('waiting', 'playing', 'matched', 'exhausted', 'closed');--> statement-breakpoint
CREATE TYPE "public"."round_status" AS ENUM('voting', 'matched', 'no_match');--> statement-breakpoint
CREATE TYPE "public"."vote_value" AS ENUM('want_to_watch', 'could_watch', 'not_now', 'no');--> statement-breakpoint
CREATE TYPE "public"."year_filter" AS ENUM('any', 'new', 'old');--> statement-breakpoint
CREATE TABLE "genres" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genres_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	CONSTRAINT "genres_name_unique" UNIQUE("name"),
	CONSTRAINT "genres_name_not_blank" CHECK (btrim("genres"."name") <> '')
);
--> statement-breakpoint
ALTER TABLE "genres" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "movie_genres" (
	"movie_id" integer NOT NULL,
	"genre_id" integer NOT NULL,
	CONSTRAINT "movie_genres_pkey" PRIMARY KEY("movie_id","genre_id")
);
--> statement-breakpoint
ALTER TABLE "movie_genres" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "movies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "movies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"release_year" smallint NOT NULL,
	"runtime_minutes" smallint NOT NULL,
	"poster_path" varchar(500),
	"available_on_netflix" boolean DEFAULT false NOT NULL,
	CONSTRAINT "movies_title_not_blank" CHECK (btrim("movies"."title") <> ''),
	CONSTRAINT "movies_release_year_check" CHECK ("movies"."release_year" >= 1888),
	CONSTRAINT "movies_runtime_minutes_check" CHECK ("movies"."runtime_minutes" > 0),
	CONSTRAINT "movies_poster_path_not_blank" CHECK ("movies"."poster_path" is null or btrim("movies"."poster_path") <> '')
);
--> statement-breakpoint
ALTER TABLE "movies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "participants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"room_id" uuid NOT NULL,
	"role" "participant_role" NOT NULL,
	"name" varchar(50) NOT NULL,
	"access_token_hash" varchar(128) NOT NULL,
	CONSTRAINT "participants_room_role_unique" UNIQUE("room_id","role"),
	CONSTRAINT "participants_room_id_id_unique" UNIQUE("room_id","id"),
	CONSTRAINT "participants_access_token_hash_unique" UNIQUE("access_token_hash"),
	CONSTRAINT "participants_name_not_blank" CHECK (btrim("participants"."name") <> ''),
	CONSTRAINT "participants_access_token_hash_check" CHECK (char_length(btrim("participants"."access_token_hash")) >= 32)
);
--> statement-breakpoint
ALTER TABLE "participants" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "room_genres" (
	"room_id" uuid NOT NULL,
	"genre_id" integer NOT NULL,
	CONSTRAINT "room_genres_pkey" PRIMARY KEY("room_id","genre_id")
);
--> statement-breakpoint
ALTER TABLE "room_genres" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(8) NOT NULL,
	"status" "room_status" DEFAULT 'waiting' NOT NULL,
	"netflix_only" boolean DEFAULT false NOT NULL,
	"under_two_hours" boolean DEFAULT false NOT NULL,
	"year_filter" "year_filter" DEFAULT 'any' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + interval '1 hour' NOT NULL,
	CONSTRAINT "rooms_code_unique" UNIQUE("code"),
	CONSTRAINT "rooms_code_format_check" CHECK ("rooms"."code" ~ '^[A-Z0-9]{4,8}$'),
	CONSTRAINT "rooms_lifetime_check" CHECK ("rooms"."expires_at" = "rooms"."created_at" + interval '1 hour')
);
--> statement-breakpoint
ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "round_movies" (
	"room_id" uuid NOT NULL,
	"round_id" uuid NOT NULL,
	"movie_id" integer NOT NULL,
	"position" smallint NOT NULL,
	"is_selected" boolean DEFAULT false NOT NULL,
	CONSTRAINT "round_movies_pkey" PRIMARY KEY("room_id","round_id","movie_id"),
	CONSTRAINT "round_movies_room_movie_unique" UNIQUE("room_id","movie_id"),
	CONSTRAINT "round_movies_round_position_unique" UNIQUE("round_id","position"),
	CONSTRAINT "round_movies_position_check" CHECK ("round_movies"."position" between 1 and 3)
);
--> statement-breakpoint
ALTER TABLE "round_movies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "rounds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"room_id" uuid NOT NULL,
	"round_number" integer NOT NULL,
	"status" "round_status" DEFAULT 'voting' NOT NULL,
	CONSTRAINT "rounds_room_round_number_unique" UNIQUE("room_id","round_number"),
	CONSTRAINT "rounds_room_id_id_unique" UNIQUE("room_id","id"),
	CONSTRAINT "rounds_round_number_check" CHECK ("rounds"."round_number" > 0)
);
--> statement-breakpoint
ALTER TABLE "rounds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "votes" (
	"room_id" uuid NOT NULL,
	"round_id" uuid NOT NULL,
	"participant_id" uuid NOT NULL,
	"movie_id" integer NOT NULL,
	"value" "vote_value" NOT NULL,
	CONSTRAINT "votes_pkey" PRIMARY KEY("room_id","round_id","participant_id","movie_id")
);
--> statement-breakpoint
ALTER TABLE "votes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "movie_genres" ADD CONSTRAINT "movie_genres_movie_id_movies_id_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "movie_genres" ADD CONSTRAINT "movie_genres_genre_id_genres_id_fk" FOREIGN KEY ("genre_id") REFERENCES "public"."genres"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participants" ADD CONSTRAINT "participants_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room_genres" ADD CONSTRAINT "room_genres_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room_genres" ADD CONSTRAINT "room_genres_genre_id_genres_id_fk" FOREIGN KEY ("genre_id") REFERENCES "public"."genres"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round_movies" ADD CONSTRAINT "round_movies_movie_id_movies_id_fk" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "round_movies" ADD CONSTRAINT "round_movies_room_round_fk" FOREIGN KEY ("room_id","round_id") REFERENCES "public"."rounds"("room_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rounds" ADD CONSTRAINT "rounds_room_id_rooms_id_fk" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "votes" ADD CONSTRAINT "votes_round_movie_fk" FOREIGN KEY ("room_id","round_id","movie_id") REFERENCES "public"."round_movies"("room_id","round_id","movie_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "votes" ADD CONSTRAINT "votes_room_participant_fk" FOREIGN KEY ("room_id","participant_id") REFERENCES "public"."participants"("room_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "movie_genres_genre_movie_idx" ON "movie_genres" USING btree ("genre_id","movie_id");--> statement-breakpoint
CREATE INDEX "room_genres_genre_room_idx" ON "room_genres" USING btree ("genre_id","room_id");--> statement-breakpoint
CREATE INDEX "rooms_active_expires_at_idx" ON "rooms" USING btree ("expires_at") WHERE "rooms"."status" <> 'closed';--> statement-breakpoint
CREATE UNIQUE INDEX "round_movies_selected_round_unique" ON "round_movies" USING btree ("round_id") WHERE "round_movies"."is_selected" = true;--> statement-breakpoint
CREATE UNIQUE INDEX "rounds_one_voting_per_room_unique" ON "rounds" USING btree ("room_id") WHERE "rounds"."status" = 'voting';--> statement-breakpoint
CREATE INDEX "votes_round_movie_idx" ON "votes" USING btree ("room_id","round_id","movie_id");--> statement-breakpoint
CREATE INDEX "votes_room_participant_idx" ON "votes" USING btree ("room_id","participant_id");--> statement-breakpoint
-- Product access stays server-only until a later feature introduces a narrowly
-- scoped browser read or Realtime policy.
revoke all privileges
on table
  "public"."genres",
  "public"."movie_genres",
  "public"."movies",
  "public"."participants",
  "public"."room_genres",
  "public"."rooms",
  "public"."round_movies",
  "public"."rounds",
  "public"."votes"
from public, anon, authenticated, service_role;--> statement-breakpoint

revoke all privileges
on sequence
  "public"."genres_id_seq",
  "public"."movies_id_seq"
from public, anon, authenticated, service_role;
