import type { MovieSeedCatalog } from "@/lib/movie-catalog/movie-seed-input";

export const movieSeedCatalogSource = {
  metadata: {
    curationNotes:
      "Titles were selected by the product owner. Release years, runtimes and genres were manually cross-checked against distributor, classification-board and established film-reference pages. Netflix availability is a conservative Ukraine-region snapshot checked on the date below; posters are intentionally omitted for v0.1.",
    netflixRegion: "UA",
    netflixVerifiedOn: "2026-09-10",
  },
  genres: [
    { key: "action", nameUk: "Бойовик" },
    { key: "adventure", nameUk: "Пригоди" },
    { key: "animation", nameUk: "Анімація" },
    { key: "comedy", nameUk: "Комедія" },
    { key: "crime", nameUk: "Кримінал" },
    { key: "documentary", nameUk: "Документальний" },
    { key: "drama", nameUk: "Драма" },
    { key: "family", nameUk: "Сімейний" },
    { key: "fantasy", nameUk: "Фентезі" },
    { key: "history", nameUk: "Історичний" },
    { key: "horror", nameUk: "Жахи" },
    { key: "music", nameUk: "Музичний" },
    { key: "mystery", nameUk: "Детектив" },
    { key: "romance", nameUk: "Мелодрама" },
    { key: "science-fiction", nameUk: "Наукова фантастика" },
    { key: "sport", nameUk: "Спортивний" },
    { key: "thriller", nameUk: "Трилер" },
    { key: "war", nameUk: "Воєнний" },
    { key: "western", nameUk: "Вестерн" },
  ],
  movies: [
    {
      seedKey: "idiocracy-2006",
      titleUk: "Ідіократія",
      releaseYear: 2006,
      runtimeMinutes: 84,
      genreKeys: ["comedy", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "obsession-2025",
      titleUk: "Обсесія",
      releaseYear: 2025,
      runtimeMinutes: 109,
      genreKeys: ["horror", "romance", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "superbad-2007",
      titleUk: "Суперперці",
      releaseYear: 2007,
      runtimeMinutes: 113,
      genreKeys: ["comedy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "good-fortune-2025",
      titleUk: "Дурна вдача",
      releaseYear: 2025,
      runtimeMinutes: 98,
      genreKeys: ["comedy", "fantasy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "jungle-2017",
      titleUk: "Джунглі",
      releaseYear: 2017,
      runtimeMinutes: 115,
      genreKeys: ["adventure", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "drivers-ed-2025",
      titleUk: "Супер Драйвер",
      releaseYear: 2025,
      runtimeMinutes: 104,
      genreKeys: ["comedy", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "coyote-vs-acme-2026",
      titleUk: "Койот проти Акме",
      releaseYear: 2026,
      runtimeMinutes: 103,
      genreKeys: ["adventure", "animation", "comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "we-live-in-time-2024",
      titleUk: "Час жити",
      releaseYear: 2024,
      runtimeMinutes: 108,
      genreKeys: ["drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "chaos-walking-2021",
      titleUk: "Дорога хаосу",
      releaseYear: 2021,
      runtimeMinutes: 109,
      genreKeys: ["action", "adventure", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-fundamentals-of-caring-2016",
      titleUk: "Основні принципи добра",
      releaseYear: 2016,
      runtimeMinutes: 97,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: true,
      poster: null,
    },
    {
      seedKey: "die-my-love-2025",
      titleUk: "Здохни, коханий",
      releaseYear: 2025,
      runtimeMinutes: 119,
      genreKeys: ["drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "united-passions-2014",
      titleUk: "Ліга мрії",
      releaseYear: 2014,
      runtimeMinutes: 110,
      genreKeys: ["drama", "history", "sport"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "good-boys-2019",
      titleUk: "Хороші хлопці",
      releaseYear: 2019,
      runtimeMinutes: 90,
      genreKeys: ["comedy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "how-to-make-a-killing-2026",
      titleUk: "Мисливець за спадком",
      releaseYear: 2026,
      runtimeMinutes: 105,
      genreKeys: ["comedy", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "in-the-grey-2026",
      titleUk: "В сірій зоні",
      releaseYear: 2026,
      runtimeMinutes: 97,
      genreKeys: ["action", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "little-miss-sunshine-2006",
      titleUk: "Маленька міс Щастя",
      releaseYear: 2006,
      runtimeMinutes: 101,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "don-jon-2013",
      titleUk: "Пристрасті Дон Жуана",
      releaseYear: 2013,
      runtimeMinutes: 90,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "pearl-harbor-2001",
      titleUk: "Перл-Гарбор",
      releaseYear: 2001,
      runtimeMinutes: 183,
      genreKeys: ["action", "drama", "history", "romance", "war"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "good-luck-have-fun-dont-die-2026",
      titleUk: "Щасти, розважся, не помри",
      releaseYear: 2026,
      runtimeMinutes: 134,
      genreKeys: ["adventure", "comedy", "science-fiction", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "kinds-of-kindness-2024",
      titleUk: "Види милосердя",
      releaseYear: 2024,
      runtimeMinutes: 164,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "sinners-2025",
      titleUk: "Грішники",
      releaseYear: 2025,
      runtimeMinutes: 138,
      genreKeys: ["action", "drama", "horror", "music"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "supergirl-2026",
      titleUk: "Суперґьорл",
      releaseYear: 2026,
      runtimeMinutes: 110,
      genreKeys: ["action", "adventure", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-departed-2006",
      titleUk: "Відступники",
      releaseYear: 2006,
      runtimeMinutes: 151,
      genreKeys: ["crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "greenland-2020",
      titleUk: "Гренландія",
      releaseYear: 2020,
      runtimeMinutes: 119,
      genreKeys: ["action", "science-fiction", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "one-battle-after-another-2025",
      titleUk: "Одна битва за іншою",
      releaseYear: 2025,
      runtimeMinutes: 162,
      genreKeys: ["action", "comedy", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "there-will-be-blood-2007",
      titleUk: "Нафта",
      releaseYear: 2007,
      runtimeMinutes: 158,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "absolute-power-1997",
      titleUk: "Абсолютна влада",
      releaseYear: 1997,
      runtimeMinutes: 121,
      genreKeys: ["crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "only-2019",
      titleUk: "Єдина",
      releaseYear: 2019,
      runtimeMinutes: 98,
      genreKeys: ["drama", "romance", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "splitsville-2025",
      titleUk: "Сплітсвіль",
      releaseYear: 2025,
      runtimeMinutes: 105,
      genreKeys: ["comedy", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "nightcrawler-2014",
      titleUk: "Стрінгер",
      releaseYear: 2014,
      runtimeMinutes: 117,
      genreKeys: ["crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "independence-day-resurgence-2016",
      titleUk: "День незалежності 2",
      releaseYear: 2016,
      runtimeMinutes: 120,
      genreKeys: ["action", "adventure", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "a-million-miles-away-2023",
      titleUk: "За мільйон миль",
      releaseYear: 2023,
      runtimeMinutes: 121,
      genreKeys: ["drama", "history"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "mainstream-2020",
      titleUk: "Мейнстрим",
      releaseYear: 2020,
      runtimeMinutes: 94,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "definitely-maybe-2008",
      titleUk: "Так, можливо",
      releaseYear: 2008,
      runtimeMinutes: 112,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "shes-out-of-my-league-2010",
      titleUk: "Надто крута для тебе",
      releaseYear: 2010,
      runtimeMinutes: 104,
      genreKeys: ["comedy", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "remember-me-2010",
      titleUk: "Пам'ятай мене",
      releaseYear: 2010,
      runtimeMinutes: 113,
      genreKeys: ["drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "robin-hood-2018",
      titleUk: "Робін Гуд",
      releaseYear: 2018,
      runtimeMinutes: 116,
      genreKeys: ["action", "adventure"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "two-for-the-money-2005",
      titleUk: "Гроші на двох",
      releaseYear: 2005,
      runtimeMinutes: 122,
      genreKeys: ["drama", "sport", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "jack-reacher-2012",
      titleUk: "Джек Річер",
      releaseYear: 2012,
      runtimeMinutes: 130,
      genreKeys: ["action", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "boxer-2024",
      titleUk: "Боксер",
      releaseYear: 2024,
      runtimeMinutes: 150,
      genreKeys: ["drama", "sport"],
      availableOnNetflix: true,
      poster: null,
    },
    {
      seedKey: "the-life-of-chuck-2024",
      titleUk: "Життя Чака",
      releaseYear: 2024,
      runtimeMinutes: 111,
      genreKeys: ["drama", "fantasy", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "spirited-2022",
      titleUk: "Дух Різдва",
      releaseYear: 2022,
      runtimeMinutes: 127,
      genreKeys: ["comedy", "family", "fantasy", "music"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "wag-the-dog-1997",
      titleUk: "Хвіст крутить собакою",
      releaseYear: 1997,
      runtimeMinutes: 97,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "burn-after-reading-2008",
      titleUk: "Прочитати та спалити",
      releaseYear: 2008,
      runtimeMinutes: 96,
      genreKeys: ["comedy", "crime", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "horrible-bosses-2011",
      titleUk: "Нестерпні боси",
      releaseYear: 2011,
      runtimeMinutes: 98,
      genreKeys: ["comedy", "crime"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "deep-water-2022",
      titleUk: "Глибокі води",
      releaseYear: 2022,
      runtimeMinutes: 115,
      genreKeys: ["drama", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "i-love-you-phillip-morris-2009",
      titleUk: "Я кохаю тебе, Філліпе Моррісе",
      releaseYear: 2009,
      runtimeMinutes: 98,
      genreKeys: ["comedy", "crime", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "dark-crimes-2016",
      titleUk: "Справжні злочини",
      releaseYear: 2016,
      runtimeMinutes: 92,
      genreKeys: ["crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "man-on-the-moon-1999",
      titleUk: "Людина на Місяці",
      releaseYear: 1999,
      runtimeMinutes: 118,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "brewsters-millions-1985",
      titleUk: "Мільйони Брюстера",
      releaseYear: 1985,
      runtimeMinutes: 102,
      genreKeys: ["comedy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-pursuit-of-happyness-2006",
      titleUk: "У гонитві за щастям",
      releaseYear: 2006,
      runtimeMinutes: 117,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-creator-2023",
      titleUk: "Творець",
      releaseYear: 2023,
      runtimeMinutes: 133,
      genreKeys: ["action", "adventure", "drama", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "last-vegas-2013",
      titleUk: "Останнє похмілля у Вегасі",
      releaseYear: 2013,
      runtimeMinutes: 105,
      genreKeys: ["comedy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "jack-the-giant-slayer-2013",
      titleUk: "Джек — вбивця велетнів",
      releaseYear: 2013,
      runtimeMinutes: 114,
      genreKeys: ["action", "adventure", "fantasy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "heads-of-state-2025",
      titleUk: "Глави держав",
      releaseYear: 2025,
      runtimeMinutes: 116,
      genreKeys: ["action", "comedy", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "eddington-2025",
      titleUk: "Еддінгтон",
      releaseYear: 2025,
      runtimeMinutes: 148,
      genreKeys: ["comedy", "drama", "western"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "manchester-by-the-sea-2016",
      titleUk: "Манчестер біля моря",
      releaseYear: 2016,
      runtimeMinutes: 137,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "weapons-2025",
      titleUk: "Зброя",
      releaseYear: 2025,
      runtimeMinutes: 128,
      genreKeys: ["horror", "mystery"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "wolfs-2024",
      titleUk: "Самотні вовки",
      releaseYear: 2024,
      runtimeMinutes: 108,
      genreKeys: ["comedy", "crime"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-hunt-2012",
      titleUk: "Полювання",
      releaseYear: 2012,
      runtimeMinutes: 115,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "from-hell-2001",
      titleUk: "Із пекла",
      releaseYear: 2001,
      runtimeMinutes: 122,
      genreKeys: ["crime", "horror", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "hell-of-a-summer-2023",
      titleUk: "Пекельне літо",
      releaseYear: 2023,
      runtimeMinutes: 88,
      genreKeys: ["comedy", "horror"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "prisoners-2013",
      titleUk: "Полонянки",
      releaseYear: 2013,
      runtimeMinutes: 153,
      genreKeys: ["crime", "drama", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "palm-springs-2020",
      titleUk: "Зависнути у Палм-Спрінгз",
      releaseYear: 2020,
      runtimeMinutes: 90,
      genreKeys: ["comedy", "fantasy", "romance", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "patrick-2018",
      titleUk: "Патрік",
      releaseYear: 2018,
      runtimeMinutes: 94,
      genreKeys: ["comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "standing-up-falling-down-2019",
      titleUk: "Стендап із приязні",
      releaseYear: 2019,
      runtimeMinutes: 91,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "dora-and-the-lost-city-of-gold-2019",
      titleUk: "Дора і загублене місто",
      releaseYear: 2019,
      runtimeMinutes: 102,
      genreKeys: ["adventure", "comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "seven-1995",
      titleUk: "Сім",
      releaseYear: 1995,
      runtimeMinutes: 127,
      genreKeys: ["crime", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "vanilla-sky-2001",
      titleUk: "Ванільне небо",
      releaseYear: 2001,
      runtimeMinutes: 136,
      genreKeys: ["drama", "mystery", "romance", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "lord-of-the-flies-1990",
      titleUk: "Володар мух",
      releaseYear: 1990,
      runtimeMinutes: 90,
      genreKeys: ["adventure", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "storks-2016",
      titleUk: "Лелеки",
      releaseYear: 2016,
      runtimeMinutes: 87,
      genreKeys: ["adventure", "animation", "comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-iron-giant-1999",
      titleUk: "Залізний велетень",
      releaseYear: 1999,
      runtimeMinutes: 86,
      genreKeys: ["adventure", "animation", "family", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "diner-1982",
      titleUk: "Закусочна",
      releaseYear: 1982,
      runtimeMinutes: 110,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "memento-2000",
      titleUk: "Пам'ятай",
      releaseYear: 2000,
      runtimeMinutes: 113,
      genreKeys: ["mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-station-agent-2003",
      titleUk: "Станційний доглядач",
      releaseYear: 2003,
      runtimeMinutes: 89,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-adventures-of-buckaroo-banzai-1984",
      titleUk: "Пригоди Бакару Банзая у 8-му вимірі",
      releaseYear: 1984,
      runtimeMinutes: 103,
      genreKeys: ["adventure", "comedy", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "funny-games-2007",
      titleUk: "Забавні ігри",
      releaseYear: 2007,
      runtimeMinutes: 111,
      genreKeys: ["crime", "drama", "horror", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-life-list-2025",
      titleUk: "Список мрій",
      releaseYear: 2025,
      runtimeMinutes: 125,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: true,
      poster: null,
    },
    {
      seedKey: "the-bad-guys-2-2025",
      titleUk: "Поганці 2",
      releaseYear: 2025,
      runtimeMinutes: 104,
      genreKeys: ["action", "adventure", "animation", "comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-iron-claw-2023",
      titleUk: "Залізний кіготь",
      releaseYear: 2023,
      runtimeMinutes: 132,
      genreKeys: ["drama", "sport"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "gone-in-60-seconds-2000",
      titleUk: "Викрасти за 60 секунд",
      releaseYear: 2000,
      runtimeMinutes: 118,
      genreKeys: ["action", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-banker-2020",
      titleUk: "Банкір",
      releaseYear: 2020,
      runtimeMinutes: 120,
      genreKeys: ["drama", "history"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "then-came-you-2018",
      titleUk: "30 шалених бажань",
      releaseYear: 2018,
      runtimeMinutes: 97,
      genreKeys: ["adventure", "comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "brothers-2009",
      titleUk: "Брати",
      releaseYear: 2009,
      runtimeMinutes: 105,
      genreKeys: ["drama", "thriller", "war"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "liberal-arts-2012",
      titleUk: "Гуманітарні науки",
      releaseYear: 2012,
      runtimeMinutes: 97,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "heretic-2024",
      titleUk: "Єретик",
      releaseYear: 2024,
      runtimeMinutes: 111,
      genreKeys: ["horror", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    { seedKey: "mud-2012", titleUk: "Мад", releaseYear: 2012, runtimeMinutes: 130, genreKeys: ["drama"], availableOnNetflix: false, poster: null },
    {
      seedKey: "beautiful-boy-2018",
      titleUk: "Гарний хлопчик",
      releaseYear: 2018,
      runtimeMinutes: 120,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "under-the-silver-lake-2018",
      titleUk: "Під Сільвер Лейк",
      releaseYear: 2018,
      runtimeMinutes: 139,
      genreKeys: ["crime", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "margin-call-2011",
      titleUk: "Межа ризику",
      releaseYear: 2011,
      runtimeMinutes: 107,
      genreKeys: ["drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "darkest-hour-2017",
      titleUk: "Темні часи",
      releaseYear: 2017,
      runtimeMinutes: 125,
      genreKeys: ["drama", "history", "war"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-town-2010",
      titleUk: "Місто",
      releaseYear: 2010,
      runtimeMinutes: 125,
      genreKeys: ["crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "anora-2024",
      titleUk: "Анора",
      releaseYear: 2024,
      runtimeMinutes: 139,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "a-complete-unknown-2024",
      titleUk: "Боб Ділан: Цілковитий незнайомець",
      releaseYear: 2024,
      runtimeMinutes: 141,
      genreKeys: ["drama", "history", "music"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-devil-wears-prada-2006",
      titleUk: "Диявол носить Прада",
      releaseYear: 2006,
      runtimeMinutes: 109,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "leon-the-professional-1994",
      titleUk: "Леон",
      releaseYear: 1994,
      runtimeMinutes: 110,
      genreKeys: ["action", "crime", "drama", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "navalny-2022",
      titleUk: "Навальний",
      releaseYear: 2022,
      runtimeMinutes: 98,
      genreKeys: ["documentary"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "enemy-2013",
      titleUk: "Ворог",
      releaseYear: 2013,
      runtimeMinutes: 91,
      genreKeys: ["drama", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "a-man-called-otto-2022",
      titleUk: "Чоловік на ім'я Отто",
      releaseYear: 2022,
      runtimeMinutes: 126,
      genreKeys: ["comedy", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "kill-bill-volume-1-2003",
      titleUk: "Убити Білла. Фільм 1",
      releaseYear: 2003,
      runtimeMinutes: 111,
      genreKeys: ["action", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "kill-bill-volume-2-2004",
      titleUk: "Убити Білла. Фільм 2",
      releaseYear: 2004,
      runtimeMinutes: 137,
      genreKeys: ["action", "crime", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "borat-subsequent-moviefilm-2020",
      titleUk: "Борат 2",
      releaseYear: 2020,
      runtimeMinutes: 96,
      genreKeys: ["comedy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "weird-the-al-yankovic-story-2022",
      titleUk: "Дивний: Історія Ела Янковича",
      releaseYear: 2022,
      runtimeMinutes: 108,
      genreKeys: ["comedy", "music"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "ad-astra-2019",
      titleUk: "До зірок",
      releaseYear: 2019,
      runtimeMinutes: 123,
      genreKeys: ["adventure", "drama", "mystery", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "dont-worry-darling-2022",
      titleUk: "Не хвилюйся, серденько",
      releaseYear: 2022,
      runtimeMinutes: 123,
      genreKeys: ["drama", "mystery", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "21-2008",
      titleUk: "Двадцять одне",
      releaseYear: 2008,
      runtimeMinutes: 123,
      genreKeys: ["crime", "drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "meet-joe-black-1998",
      titleUk: "Знайомтеся — Джо Блек",
      releaseYear: 1998,
      runtimeMinutes: 181,
      genreKeys: ["drama", "fantasy", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "crazy-stupid-love-2011",
      titleUk: "Це безглузде кохання",
      releaseYear: 2011,
      runtimeMinutes: 118,
      genreKeys: ["comedy", "drama", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "whats-eating-gilbert-grape-1993",
      titleUk: "Що гнітить Гілберта Грейпа",
      releaseYear: 1993,
      runtimeMinutes: 118,
      genreKeys: ["drama"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "teenage-mutant-ninja-turtles-mutant-mayhem-2023",
      titleUk: "Підлітки-мутанти Черепашки-ніндзя: Погром мутантів",
      releaseYear: 2023,
      runtimeMinutes: 99,
      genreKeys: ["action", "adventure", "animation", "comedy", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "her-2013",
      titleUk: "Вона",
      releaseYear: 2013,
      runtimeMinutes: 126,
      genreKeys: ["drama", "romance", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "the-tomorrow-war-2021",
      titleUk: "Війна завтрашнього дня",
      releaseYear: 2021,
      runtimeMinutes: 138,
      genreKeys: ["action", "adventure", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "red-eye-2005",
      titleUk: "Нічний рейс",
      releaseYear: 2005,
      runtimeMinutes: 85,
      genreKeys: ["thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "along-with-the-gods-the-two-worlds-2017",
      titleUk: "З Богами: Два світи",
      releaseYear: 2017,
      runtimeMinutes: 139,
      genreKeys: ["action", "adventure", "drama", "fantasy"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "knowing-2009",
      titleUk: "Знамення",
      releaseYear: 2009,
      runtimeMinutes: 121,
      genreKeys: ["action", "mystery", "science-fiction", "thriller"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "everything-everywhere-all-at-once-2022",
      titleUk: "Все завжди і водночас",
      releaseYear: 2022,
      runtimeMinutes: 139,
      genreKeys: ["action", "adventure", "comedy", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "we-bought-a-zoo-2011",
      titleUk: "Ми купили зоопарк",
      releaseYear: 2011,
      runtimeMinutes: 124,
      genreKeys: ["comedy", "drama", "family"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "spider-man-across-the-spider-verse-2023",
      titleUk: "Людина-павук: По той бік Всесвіту",
      releaseYear: 2023,
      runtimeMinutes: 140,
      genreKeys: ["action", "adventure", "animation", "science-fiction"],
      availableOnNetflix: false,
      poster: null,
    },
    {
      seedKey: "hit-man-2023",
      titleUk: "Хітмен",
      releaseYear: 2023,
      runtimeMinutes: 115,
      genreKeys: ["comedy", "crime", "romance"],
      availableOnNetflix: false,
      poster: null,
    },
  ],
} satisfies MovieSeedCatalog;
